api_platform:
    title: Quiz Master
    version: 1.0.0
    formats:
        json: ['application/json']
#        jsonld: [ 'application/json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
